name: dataset-tools
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - opencv
  - scipy
  - open3d
  - scikit-learn
  - manifpy
  - tqdm
  - pyyaml
  - natsort
  - matplotlib
  - pandas
  - rosbags