name: dataset-tools
channels:
  - conda-forge
dependencies:
  - python=3.11
  - manifpy
  - opencv
  - numpy<2
  - scipy
  - open3d
  - scikit-learn
  - pyyaml
  - matplotlib
  - pandas
  - natsort
  - rosbags
  - loguru
  - tqdm