bagfile_root: /home/quattro/ut-amrl
output_root: /home/quattro/ut-amrl

topics:
  /wanda/sensors/multisense_front/aux/image_rect_color:
    format: image
    outdir: image_raw
  /wanda/sensors/multisense_front/left/depth:
    format: depth
    outdir: depth
  /wanda/platform/odom:
    format: csv
    outpath: odom_platform.csv
  /wanda/sensors/ublox/fix:
    format: csv
    outpath: gps.csv

scenes:
  507_run_00:
    bagfiles:
      - run_00_bev-patch-logging_2026-03-09-13-47-12
    start: 0
    end: -1
