bagfile_root: /path/to/bagfiles
output_root: /path/to/output/lonebot

topics:
  /lonebot/sensors/realsense/camera/color/image_raw/compressed:
    format: image
    outdir: image_raw
  /lonebot/sensors/realsense/camera/depth/image_rect_raw:
    format: depth
    outdir: depth
  /lonebot/platform/odom:
    format: csv
    outpath: odom_platform.csv
  /lonebot/bev_patch_pf/odom:
    format: csv
    outpath: bev_patch_pf.csv
  /lonebot/sensors/ublox/fix:
    format: csv
    outpath: gps.csv

scenes:
  example_eastwood_run_00:
    bagfiles:
      - eastwood/example_run_00
    start: 0
    end: -1

  example_eastwood_run_01:
    bagfiles:
      - eastwood/example_run_01
    start: 0
    end: -1
