bagfile_root: /robodata/dlee/Datasets/ahg-courtyard/bagfiles
output_root: /robodata/dlee/Datasets/ahg-courtyard

topics:
  /bluebonnet/sensors/camera/bluebonnet_realsense/color/image_raw:
    format: image
    outdir: image_raw
  /bluebonnet/sensors/camera/bluebonnet_realsense/depth/image_rect_raw:
    format: depth
    outdir: depth
  /bluebonnet/odometry/local:
    format: csv
    outpath: odom_local.csv
  /bluebonnet/sensors/ublox/fix:
    format: csv
    outpath: gps.csv

bag_list:
  - file: rosbag2_2025_07_03-18_09_49
    name: 2025_07_03-18_09_49
    start: 0
    end: -1
  - file: rosbag2_2025_07_03-18_17_34
    name: 2025_07_03-18_17_34
    start: 1751581068.0
    end: -1
