bagfile_root: /robodata/ARL_SARA/GQ-dataset/bagfiles
output_root: /robodata/dlee/Datasets/GQ-dataset

topics:
  /trevor/odom:
    format: csv
    outdir: odom
  /trevor/warthog_velocity_controller/cmd_vel:
    format: csv
    outdir: velocity_control
  /trevor/warthog_velocity_controller/cmd_vel_out:
    format: csv
    outdir: velocity_control_stamped
  /trevor/gps:
    format: csv
    outdir: gps
  /trevor/stereo_left/image_rect_color/compressed:
    format: image
    outdir: 2d_raw
    sub: cam_left
  /trevor/stereo_right/image_rect_color/compressed:
    format: image
    outdir: 2d_raw
    sub: cam_right
  /trevor/multisense_forward/left/image_rect:
    format: image
    outdir: multisense
    sub: forward_left
  /trevor/multisense_forward/right/image_rect:
    format: image
    outdir: multisense
    sub: forward_right
  /trevor/multisense_rear/left/image_rect:
    format: image
    outdir: multisense
    sub: rear_left
  /trevor/multisense_rear/right/image_rect:
    format: image
    outdir: multisense
    sub: rear_right

bag_list:
  - name: data_collect_2025-02-28-13-46-54
    file: data_collect_2025-02-28-13-46-54.bag
    start: 0
    end: -1
  - name: data_collect_2025-02-28-13-59-10
    file: data_collect_2025-02-28-13-59-10.bag
    start: 0
    end: -1
